### ISSUE TITLE
Account name listed as "Riot user"

### ISSUE THREAD

**Issue by Rhin94** [urwrstkn8mare/gog-riot-integration#12]
I added the plugin using the instructions provided and wasn't prompted to login or anything and it now shows my username as "Riot User"
![image](https://user-images.githubusercontent.com/58856839/101776899-8cdcbe80-3ae9-11eb-8c77-f7adfbc00816.png)

Log attached

**Comment by Rhin94** [comment]
[plugin-riot-b4c0c2f5-23dc-4326-aa65-e9fabef61a3b.log](https://github.com/urwrstkn8mare/galaxy-riot-integration/files/5672957/plugin-riot-b4c0c2f5-23dc-4326-aa65-e9fabef61a3b.log)

**Comment by urwrstkn8mare** [comment]
Yes, that is expected and the intended functionality. Your Riot username isn't required to detect, install, run, or track playtime for any Riot game. In the future, however, you will be able to see your Riot username when I add these features: #9 & #7. Sorry for any confusion. Feel free to reply to this if you have any other questions.
