### ISSUE TITLE
Games can not be launched after closing GoG Galaxy

### ISSUE THREAD

**Issue by Dogo314** [urwrstkn8mare/gog-riot-integration#16]
(As version 2.4 isnt working for me I use 2.3 even after doing all of the steps carefully a few times) After the plugin is installed and it works as expected I fully close GoG Galaxy. After opening it all of the plugin's games are shown as "Install" in grey and the only way to fix it is to connect it again in the setting.
<img width="388" alt="a79dc2e30b0843133f78717a948c6150" src="https://user-images.githubusercontent.com/77802524/105394530-00600880-5c1e-11eb-827a-4de60d9a2501.png">
Thanks for your help!

**Comment by BanCrash** [comment]
I think this is the same issue as #10 , wich unfortunately is not solved yet.

**Comment by urwrstkn8mare** [comment]
Yeah it is the same issue so I'll leave close this one but the other one (#10) will remain open.
