### ISSUE TITLE
"riot user" 

### ISSUE THREAD

**Issue by bara9880** [urwrstkn8mare/gog-riot-integration#2]
![image](https://user-images.githubusercontent.com/58350309/84548008-5f1ae680-ad0d-11ea-975d-ebb6a2f28c89.png)
its not showing my account name , i'm guessing this is because you are not really connected to the account , just the local files right ?

**Comment by urwrstkn8mare** [comment]
Thanks for asking and yes, I can't use the actual account information for much except for league friends. Riot playtime, for example, isn't stored by Riot so I have to do that myself. About league friends, I might implement that at a later time but I don't have enough time as of now. If you'd like to give it a go and get it working I'd appreciate a pull request!
