### ISSUE TITLE
tasks.py requires update

### ISSUE THREAD

**Issue by BlazingMarauder** [urwrstkn8mare/gog-riot-integration#29]
Pipenv has removed the `-r` flag from pipenv lock as seen here:

![image](https://user-images.githubusercontent.com/50110207/214611467-92568339-c1f3-4943-9c34-2bea1ad3d9a5.png)

also, `CONTRIBUTING.md` references a `build.py` instead of `tasks.py`.

If I am completely off mark with this issue, feel free to disregard and close the issue

**Comment by urwrstkn8mare** [comment]
Thanks for the heads up!
