### ISSUE TITLE
The Plugin is crashing for me

### ISSUE THREAD

**Issue by AcePhire** [urwrstkn8mare/gog-riot-integration#4]
![image](https://user-images.githubusercontent.com/46824456/85944333-9e1c7f00-b93e-11ea-8792-5bd6ede9bb15.png)

**Comment by AcePhire** [comment]
Never mind I was able to fix it by placing this:
![image](https://user-images.githubusercontent.com/46824456/85944769-1769a100-b942-11ea-8895-d9975f4541c9.png)

into a .txt file and removing the "python3", then changing the file into a .py and ran the file.

Sorry if this was something obvious to do, I just found out that GOG Galaxy has plugins.

**Comment by urwrstkn8mare** [comment]
Good to know its fixed. Just so I know, how did you download the plugin? From releases or just cloning the repo?

**Comment by AcePhire** [comment]
By cloning

**Comment by urwrstkn8mare** [comment]
That would be why. Galaxy requires packages to be packaged with the plugin. The packages are not in the repo but they are included in the releases. However, your method of cloning and including the packages yourself also works. Just downloading the release is easier. Thanks for letting me know.
