### ISSUE TITLE
Plugin Crash on Galaxy2.0.18.56 Beta

### ISSUE THREAD

**Issue by GildartsClive** [urwrstkn8mare/gog-riot-integration#5]
The plugin crashes when you click the Connect button and will crash when you click retry.

**Comment by urwrstkn8mare** [comment]
Thnx for reporting this, I would also appreciate the log file for the plugin. I will try to look at it ASAP.

**Comment by GildartsClive** [comment]
if you could help me learn where I can look for something like that I would love to give you the log file for it.

**Comment by urwrstkn8mare** [comment]
You can find it in `%programdata%\GOG.com\Galaxy\logs` it should have the word `riot` in the name of the log file. There may be lots of logs in that folder you will just have to look for it. A little tip to make it easier would be to sort by date modified.

**Comment by GildartsClive** [comment]
got it here you go
[
[plugin-riot-b4c0c2f5-23dc-4326-aa65-e9fabef61a3b.log](https://github.com/urwrstkn8mare/galaxy-riot-integration/files/4969414/plugin-riot-b4c0c2f5-23dc-4326-aa65-e9fabef61a3b.log)
](url)

**Comment by urwrstkn8mare** [comment]
Thnx, I can see a big issue, it can't access the requests module. This should not be a problem as requests should be packaged with the plugin. How did you install the plugin? It's highly likely its something to do with that. 

Downloading it from here in [releases](https://github.com/urwrstkn8mare/galaxy-riot-integration/releases) should do the trick. 
![image](https://user-images.githubusercontent.com/42769125/88348204-622edb00-cd7f-11ea-8972-2fc08411dc8c.png)

**Comment by GildartsClive** [comment]
that is how I did it but I will try again

**Comment by GildartsClive** [comment]
So I reinstalled it the same way I did the first time and it is working now, thanks for the help.

**Comment by urwrstkn8mare** [comment]
Happy to help. 

Just to add - if you were looking for more info - from looking at your logs, I think you may have downloaded it via the Source code link as the folder in the installed directory should be called: `gog-riot-integration-windows`. Instead I saw `galaxy-riot-integration\` and `riot_b4c0c2f5-23dc-4326-aa65-e9fabef61a3b\`. You could have gotten the first folder name from downloading the source code (`Source code (zip)` - second link in releases) as that is the new name for the repo while the release file I attached still uses gog-riot-integration name. The second name with the GUID I'm not quite sure.
